apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification.fullname" . }}-secret
  labels: {{- include "notification.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.immutable.enabled }}
immutable: true
{{- end }}
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
  FLUENTD_USER: {{ default "" .Values.logging.fluentd.elasticsearch.user | quote }}
  FLUENTD_PWD: {{ default "" .Values.logging.fluentd.elasticsearch.password | quote }}