apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification.fullname" . }}
  labels: {{- include "notification.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: 5025
      targetPort: 5025
  selector:
    app: {{ include "notification.fullname" . }}